#!/bin/sh

# settings
version=3.18
arch=aarch64

distro_tar=~/.cache/nenv/distro/alpine-$version-$arch.tar.gz

if [ -z $1 ]; then
  echo "requires 1 argument (environment name)"
  return 1
fi

root=$1

if [ -e $root ]; then
  echo "file/directory $root already exist"
  return 1
fi

echo "creating new environment: $root"

if [ ! -f $distro_tar ]; then

  echo "creating cache directory... (~/.cache/nenv/distro)"
  mkdir -p ~/.cache/nenv/distro

  echo "downloading tar..."
  curl https://dl-cdn.alpinelinux.org/alpine/v$version/releases/$arch/alpine-minirootfs-$version.0-$arch.tar.gz -o $distro_tar

else

  echo "cached tar found..."

fi

mkdir -p $root

echo "extracting environment..."
tar -xf $distro_tar --directory $root

echo "setting up environment..."
echo "nameserver 1.1.1.1" > $root/etc/resolv.conf

echo "new environment created: $root"

return 0
